### ISSUE TITLE
Menu: remove 'dribble' icon

### ISSUE THREAD

**Issue by rskikuli** [JoraKasapi/jorakasapi.github.io#12]
Since you @JoraKasapi, in my knowledge do not have a 'Dribble' account, I would advice to remove this icon and replace it with something else (Twitter or Instagram?).

**Comment by rskikuli** [comment]
In some pages it has been removed such as this one: https://jorakasapi.github.io/contact.html. I assume you have to do the same process with the other pages as well.

**Comment by JoraKasapi** [comment]
I removed the dribble account and left the linked in only and made it possible for it to direct you to the linkedin account
